"""add provider and model_name to Conversation

Revision ID: 2f120675e312
Revises: 
Create Date: 2025-06-08 12:25:31.973115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f120675e312'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('provider', sa.String(), nullable=False , server_default='ollama'))
    op.add_column('conversations', sa.Column('model_name', sa.String(), nullable=False , server_default='llama3.2:1b-instruct-q8_0'))
    # op.alter_column('conversations', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)
    # op.alter_column('messages', 'timestamp',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('messages', 'timestamp',
    #            existing_type=sa.DATETIME(),
    #            nullable=True)
    # op.alter_column('conversations', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=True)
    op.drop_column('conversations', 'model_name')
    op.drop_column('conversations', 'provider')
    # ### end Alembic commands ###
